/**
 * Migration: project_work_orders table.
 *
 * Pat: "i also want to add in a Work Order Template ... the system
 * should automatically create one when a project is created, and when
 * anyone of the project lines are edited it should create a copy".
 *
 * Versioned PDF history per project. Each row is one snapshot of the
 * project's contact + location + numbering data at a moment in time.
 *
 * Row shape:
 *   id              uuid
 *   project_id      uuid → projects.id (ON DELETE CASCADE)
 *   version         int        sequential within the project (1, 2, 3, …)
 *   file_path       text       absolute path on the api container's disk
 *   content_hash    text       SHA-256 of the render inputs (dedupe no-ops)
 *   generated_at    timestamptz default now
 *   generated_by_user_id  uuid (nullable — null when auto-generated by a trigger
 *                                with no user context, e.g. cron)
 *   created_at      timestamptz default now
 *
 * Unique on (project_id, version) so the version sequence stays clean.
 * Unique on (project_id, content_hash) so a non-substantive edit doesn't
 * create a duplicate row (PR description: "no-op saves via content_hash
 * dedupe").
 *
 * IDEMPOTENT — guarded by hasTable.
 */

exports.up = async function (knex) {
  const exists = await knex.schema.hasTable('project_work_orders');
  if (exists) {
    console.log('  (project_work_orders already present — skipping)');
    return;
  }
  await knex.schema.createTable('project_work_orders', (t) => {
    t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    t.uuid('project_id').notNullable().references('id').inTable('projects').onDelete('CASCADE');
    t.integer('version').notNullable();
    t.text('file_path').notNullable();
    t.text('content_hash').notNullable();
    t.timestamp('generated_at', { useTz: true }).defaultTo(knex.fn.now());
    t.uuid('generated_by_user_id').nullable().references('id').inTable('users').onDelete('SET NULL');
    t.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    t.unique(['project_id', 'version']);
    t.unique(['project_id', 'content_hash']);
    t.index('project_id');
  });
  console.log('  ✅ project_work_orders table created');
};

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists('project_work_orders');
};
